spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cooking_mama?serverTimezone=UTC
    username: root
    password: 1234

mybatis:
  config-location: classpath:mybatis/config/config.xml

spring-doc:
  swagger-ui:
    path: /swagger-ui.html